### ISSUE TITLE
Everyone can add any language to "known languages"

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/Novis-Station#13]
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round

**Comment by Nightspark43** [comment]
I'll look at this one, I know where to look for most of the language code.

**Comment by JakeDaBoss** [comment]
For reference, this is in char setup.

**Comment by Nightspark43** [comment]
Make sure you're not just seeing it as an admin,

**Comment by Nightspark43** [comment]
I know Admins in Bay can select any language.

**Comment by JakeDaBoss** [comment]
I'll check it out.

**Comment by Nightspark43** [comment]
Found the issue, the languages were listed as Whitelisted while we don't have a whitelist, pretty sure that's the problem.

**Comment by ghost** [comment]
Set all languages you want to be race specific to RESTRICTED not white listed.

**Comment by Nightspark43** [comment]
PR for it up, took a nap before doing it for some reason.
