### ISSUE TITLE
Roid Generation broken

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/Novis-Station#17]
Doesn't generate ores.

**Comment by JakeDaBoss** [comment]
@Lykayos

**Comment by JakeDaBoss** [comment]
Needs fixing ASAP.

**Comment by JakeDaBoss** [comment]
Test

**Comment by JakeDaBoss** [comment]
Details of the issue;

Asteroid is filled with "mask" and does not generate rocks nor ore.

**Comment by MistakeNot4892** [comment]
Make sure you have the config option set and that the generation calls are targetting the right z-level.

**Comment by JakeDaBoss** [comment]
Done that @Zuhayr 
No chiz.

**Comment by JakeDaBoss** [comment]
Fixed in #23
