### ISSUE TITLE
Holodeck depressurises when activated

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/Novis-Station#25]
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by BlueNexus** [comment]
Follow the proper issue template please, without deleting parts of it.

**Comment by ghost** [comment]
#35 Forgot to tag this in the PR.
