### ISSUE TITLE
Antag creation Panel (user-end) allows every species.

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/Novis-Station#28]
https://gyazo.com/1484798cc1308f49841ae9653c3627bf

**Comment by BlueNexus** [comment]
Follow the issue template please.

**Comment by JakeDaBoss** [comment]
This is closed. Admins get the full monty. I've gotten some adjustments on the species, though, to make sure it doesn't happen to users.

Admins should be smart enough not to choose a Xeno Hunter Wizard @Nightspark43 . Anyone who's caught abusing their freedom will have it reined in, simple.
