### ISSUE TITLE
AI Upload turrets fire into Command.

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/Novis-Station#32]

**Comment by BlueNexus** [comment]
Follow the issue template please. You have provided no information with which I can either reproduce this issue or figure out why it happens. With the template, type _UNDER_ each title.

**Comment by JakeDaBoss** [comment]
The template is something I only use if it's an issue that needs explaining since that's what it's for. This is a map issue and mostly a reminder to myself.
