### ISSUE TITLE
Comms don't seem to work properly.

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/Novis-Station#33]
They shut off after a bit, even though t-comms is fine.

**Comment by BlueNexus** [comment]
Follow the issue template please. It is possible this is due to the ionospheric anomaly event, which is very common. I don't know, because you haven't followed the template.

**Comment by JakeDaBoss** [comment]
It's not the ion.

**Comment by JakeDaBoss** [comment]
This is a feature it seems like. They need to be probed. Any staff, see the note JTDrow left.
