### ISSUE TITLE
Incorrect access and lack of contents in down stair medical closets

### ISSUE THREAD

**Issue by Jtdrow** [JakeDaBoss/Novis-Station#40]
#### Description of issue

Medical Doctors are unable to unlock first aid closets. Both the locked and open versions also have no contents inside.
#### Difference between expected and actual behavior

Medical Doctors should be able to open cabinets as well as the cabinets needing to store important equipment.
#### Specific information for locating

First aid closets: /obj/structure/closet/medical_wall 
Locked first aid closets: /obj/structure/closet/secure_closet/medical_wall 
#### Length of time in which bug has been known to occur

Since server launch.
#### Server revision & Game ID

Revision unknown
Game ID: bKU-dpEi
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
I may have placed the wrong variants. I'll look at this tomorrow.

**Comment by JakeDaBoss** [comment]
Fixed. Open a new issue if there's another problem.
