### ISSUE TITLE
End of round Math not handled properly.

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/Novis-Station#54]
#### Description of issue

https://4stor.com/mal4F

Says survivors (none transferred) every round.
#### Difference between expected and actual behavior

Should be displaying the accurate amount of people that evacuated.
#### Steps to reproduce

Call shuttle, end round with live people.
#### Length of time in which bug has been known to occur

Since the start of the server.
#### Server revision & Game ID

N/A
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by BlueNexus** [comment]
This was fixed by baystation a while ago. You should probably pull in their changes (Pull, not recommit pretending you did it yourself)

**Comment by JakeDaBoss** [comment]
Do it yourself?
